[module/fanspeed]
type = custom/script
exec = ~/.config/polybar/polybar-fanspeed/fanspeed.sh
tail = true

format = <label>
format-prefix = 
format-background = ${color.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
