[module/title]
type = internal/xwindow

; Available tags:
;   <label> (default)
format = <label>
format-background = ${color.background}
format-padding = 0
;format-prefix = 

; Available tokens:
;   %title%
; Default: %title%
label = "%title%"
label-maxlen = 80

; Used instead of label when there is no window title
label-empty = VRS-Factory
