---
- name: VRS | Additional utils and packages
  block:
    - name: Polkit & keyring things
      aur:
        name:
          - polkit
          - gnome-keyring
          - libsecret
          - libgnome-keyring
    - name: IDE & editors
      aur:
        name:
          - visual-studio-code-bin
          - jetbrains-toolbox
    - name: Browsers
      aur:
        name:
          - brave-bin
          - firefox
          - google-chrome
    - name: Work
      aur:
        name:
          - mattermost-desktop
          - openvpn3
    - name: Fonts
      aur:
        name:
          - terminus-font
          - otf-font-awesome
    - name: Hardware
      aur:
        name:
          - thinkfan
          - lm_sensors
    - name: Global
      aur:
        name:
          - zip
          - unzip
          - slurp
          - neofetch
          - fzf
          - mc
          - iwd
          - kbd
          - thunderbird
    - name: DevOps
      aur:
        name:
          - vault
          - terraform
    - name: Media
      aur:
        name:
          - vlc
          - playerctl
          - spotify
