---
- name: Install Yay dependencies
  community.general.pacman:
    name: 
      - git 
      - base-devel
    state: present

- name: Download the newest Yay from repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ srcdir }}/yay"
    update: true

- name: Build & install Yay
  command:
    chdir: "{{ srcdir }}/yay"
    cmd: makepkg -sfi --noconfirm
    creates: /usr/bin/yay

# pacman -S --needed git base-devel
# git clone https://aur.archlinux.org/yay.git
# cd yay
# makepkg -si
