---
- name: VRS | System
  block:
  - name: System full-upgrade
    aur:
      update_cache: yes
      upgrade: yes

  - name: Prepare tmp directory for Ansible
    command:
      cmd: mkdir -p "{{ homedir }}/vrs-ansible"

  - name: Preapre tmp directory for yay
    command:
      cmd: mkdir -p "{{ homedir }}/vrs-ansible/yay"
