### Variables

# Logo key. Use Mod1 for Alt.
set $mod Mod4
set $alt Mod1

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Your preferred terminal emulator
set $term alacritty

# Your preferred application launcher
# Note: pass the final command to swaymsg so that the resulting window can be opened
# on the original workspace that the command was run on.
set $menu _JAVA_AWT_WM_NONREPARENTING=1 wofi --conf ~/.config/wofi/config ---allow-images --insensitive
set $menu_ssh rofi -show ssh

# Displays
set $laptop eDP-1
set $d_office_left "Dell Inc. DELL S2340L 5FYJ53BK07AT" "Dell Inc. DELL U2421HE J2L8223" "Dell Inc. DELL U2421HE GX1K123"
set $d_office_right "Dell Inc. DELL S2340L 5FYJ532S0CGT" "Dell Inc. DELL U2421HE DT2K123" "Dell Inc. DELL U2421HE 94L8223"
