###############################
######  AUTOSTART
###########################

exec_always ~/.config/sway/bin/lid-control.sh

#exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec_always --no-startup-id workstyle &> /tmp/workstyle.log

#exec --no-startup-id pkexec ~/.config/sway/bin/thinkfan.sh
exec --no-startup-id swaymsg 'workspace 1; exec mattermost-desktop; workspace 2; exec thunderbird; workspace 4; exec $term;'
exec nm-applet --indicator



# Some defaults
exec ~/.config/sway/bin/assign-cgroups.py
exec ~/.config/sway/bin/session.sh --with-cleanup

## exec /usr/libexec/sway-systemd/assign-cgroups.py
## exec /usr/libexec/sway-systemd/session.sh --with-cleanup
