### Idle configuration
#
# Example configuration:
#
#exec swayidle -w \
#         timeout 30 'swaylock -f -c 000000' \
#         #timeout 30 '/home/vertisan/.config/sway/bin/lockscreen.sh' \
#         timeout 45 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
#         before-sleep 'swaylock -f -c 000000'
#
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
#
for_window [class=.*] inhibit_idle fullscreen
for_window [title="Meet - .*-.*-.*"] inhibit_idle visible
for_window [title=".* - YouTube - .*"] inhibit_idle visible
for_window [title=".* - CDA - .*"] inhibit_idle visible
for_window [title=".*  » Bajeczki.org -.*"] inhibit_idle visible
for_window [title="Prime Video: .*"] inhibit_idle visible
for_window [title="Netflix - .*"] inhibit_idle visible
for_window [title="Disney+ | .*"] inhibit_idle visible
for_window [title=".*Picture in picture.*"] floating enable, move position 877 450, sticky enable, inhibit_idle visible
#for_window [name=".*Picture in picture.*"] floating enable, move position 877 450, sticky enable, inhibit_idle visible
for_window [app_id="^gnome-calculator$"] floating enable, move position 877 450, sticky enable
for_window [app_id="^telegramdesktop$"] floating enable, resize set 1200 900, sticky enable
for_window [class="jetbrains-toolbox"] floating enable, resize set 1200 900, sticky enable
