### Idle configuration

for_window [app_id="^org.gnome.Calculator$"] floating enable, move position 877 450, sticky enable
for_window [title="^Screen Recorder - Scre.io$"] floating enable, sticky enable
for_window [app_id="^telegramdesktop$"] floating enable, resize set 1200 900, sticky enable
for_window [class="jetbrains-toolbox"] floating enable, resize set 1200 900, sticky enable

# for_window [title="^HBO Max - .*"] inhibit_idle visible
# for_window [title="^Meet .*"] inhibit_idle visible
# for_window [title="^Disney+ | .*"] inhibit_idle visible
# for_window [title=".* - YouTube - .*"] inhibit_idle visible

for_window [title=".* - wszystkie odcinki anime online.*"] inhibit_idle visible
# for_window [title=".*  » Bajeczki.org -.*"] inhibit_idle visible
# for_window [title="Prime Video: .*"] inhibit_idle visible
for_window [title="Netflix - .*"] inhibit_idle visible
# for_window [title=".*Picture in picture.*"] floating enable, move position 877 450, sticky enable, inhibit_idle visible
