---
- name: VRS Environment
  hosts: localhost
  vars:
    homedir: "{{ lookup('env', 'HOME') }}"
    srcdir: "{{ homedir }}/vrs-ansible"
    envdir: "{{ homedir }}/Environment"
    user_config_dir: "{{ homedir }}/.config"
    username: "{{ lookup('env', 'USER') }}"

  roles:
    - { role: utils, tags: "utils" }
    - { role: git, tags: "git" }
    - { role: yay, tags: "yay" }
    # - { role: system, tags: 'system' }
    - { role: zsh, tags: "zsh" }
    - { role: alacritty, tags: "alacritty" }
    - { role: sway, tags: "sway" }
    - { role: kanshi, tags: "kanshi" }
    - { role: mako, tags: "mako" }
    - { role: neovim, tags: "neovim" }
    - { role: nwg-bar, tags: "nwg-bar" }
    - { role: nodejs, tags: "nodejs" }
    - { role: wal, tags: "wal" }
